/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package currencyConvert;

/**
 *
 * @author Mohammed Ghoul
 */
public class currencyConverter extends javax.swing.JFrame {

    /**
     * Creates new form currencyConverter
     */
    public currencyConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        convBtn = new javax.swing.JButton();
        amountLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        amountTxt = new javax.swing.JTextField();
        fromBox = new javax.swing.JComboBox<>();
        toBox = new javax.swing.JComboBox<>();
        resTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        resBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        convBtn.setText("Convert");
        convBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convBtnActionPerformed(evt);
            }
        });

        amountLabel.setText("Amount :");

        fromLabel.setText("From :");

        toLabel.setText("To :");

        fromBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DZD", "USD", "EUR", "SAR", "CNY" }));

        toBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "DZD", "EUR", "SAR", "CNY" }));

        jLabel1.setText("Resault :");

        resBtn.setText("Reset");
        resBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(amountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fromLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resBtn)
                        .addGap(18, 18, 18)
                        .addComponent(convBtn))
                    .addComponent(amountTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 210, Short.MAX_VALUE)
                    .addComponent(toBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resTxt, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLabel)
                    .addComponent(amountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromLabel)
                    .addComponent(fromBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toLabel)
                    .addComponent(toBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convBtn)
                    .addComponent(resBtn))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void convBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convBtnActionPerformed
        // TODO add your handling code here:
        Double tot;
        Double amount = Double.parseDouble(amountTxt.getText());
        String fromCurrency = fromBox.getSelectedItem().toString();
        String toCurrency = toBox.getSelectedItem().toString();

        switch (fromCurrency + toCurrency) {
            //DZD
            case "DZDUSD":
                tot = amount * 0.0074232861;
                resTxt.setText(tot.toString());
                break;
            case "DZDEUR":
                tot = amount * 0.0068822621;
                resTxt.setText(tot.toString());
                break;
            case "DZDSAR":
                tot = amount * 0.027841857;
                resTxt.setText(tot.toString());
                break;
            case "DZDCNY":
                tot = amount * 0.053283992;
                resTxt.setText(tot.toString());
                break;
            
            //USD    
            case "USDDZD":
                tot = amount * 134.68954;
                resTxt.setText(tot.toString());
                break;
            case "USDEUR":
                tot = amount * 0.92702528;
                resTxt.setText(tot.toString());
                break;
            case "USDSAR":
                tot = amount * 3.75;
                resTxt.setText(tot.toString());
                break;
            case "USDCNY":
                tot = amount * 7.1781411;
                resTxt.setText(tot.toString());
                break;
            
            //EURO    
            case "EURDZD":
                tot = amount * 145.30127;
                resTxt.setText(tot.toString());
                break;
            case "EURUSD":
                tot = amount * 1.0787909;
                resTxt.setText(tot.toString());
                break;
            case "EURSAR":
                tot = amount * 4.0454659;
                resTxt.setText(tot.toString());
                break;
            case "EURCNY":
                tot = amount * 7.7403534;
                resTxt.setText(tot.toString());
                break;
            //SAR
            case "SARDZD":
                tot = amount * 35.917008;
                resTxt.setText(tot.toString());
                break;
            case "SARUSD":
                tot = amount * 0.26666667;
                resTxt.setText(tot.toString());
                break;
            case "SAREUR":
                tot = amount * 0.24707764;
                resTxt.setText(tot.toString());
                break;
            case "SARCNY":
                tot = amount * 1.9137227;
                resTxt.setText(tot.toString());
                break;
            //CNY
            case "CNYDZD":
                tot = amount * 18.767182;
                resTxt.setText(tot.toString());
                break;
            case "CNYUSD":
                tot = amount * 0.13933669;
                resTxt.setText(tot.toString());
                break;
            case "CNYEUR":
                tot = amount * 0.12909123;
                resTxt.setText(tot.toString());
                break;
            case "CNYSAR":
                tot = amount * 0.52251258;
                resTxt.setText(tot.toString());
                break;    
            default:
                tot = amount * 1;
                resTxt.setText(tot.toString());
                break;
}

    }//GEN-LAST:event_convBtnActionPerformed

    private void resBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resBtnActionPerformed
        // TODO add your handling code here:
        amountTxt.setText("");
        resTxt.setText("");
    }//GEN-LAST:event_resBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currencyConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField amountTxt;
    private javax.swing.JButton convBtn;
    private javax.swing.JComboBox<String> fromBox;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton resBtn;
    private javax.swing.JTextField resTxt;
    private javax.swing.JComboBox<String> toBox;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables
}
